### ISSUE TITLE
switch create-react-app to vite

### ISSUE THREAD

**Issue by sansx** [Wulf/create-rust-app#3]
hey, I noticed that you use `create-react-app` to develop frontend, do you have interest switch that to vite, not only vite is lightly, but also it has a awesome plugin can compile you web into wasm [vite-plugin-rsw](https://github.com/lencx/vite-plugin-rsw)

**Comment by Wulf** [comment]
hi Sansx, sorry for the late reply. I actually read your issue a week ago or so but I had to think about it and investigate "vite". It's my first time hearing about it and I imagine it's easy to swap in for people who know about it. I think it's just a matter of:

1) deleting the contents of the frontend folder and generating one with vite's project generator, and,
2) having the vite project compile to the build directory that `create-rust-app` expects.

I'm not opposed to having an option to use vite but that means someone will have to support it as we move forward.

**Comment by sansx** [comment]
yes, I know you meaning, I'd like give support to this part, it likely I'll make a pr this month. :D 
( I'm not very familiar with this project, which I might need help in some ways )

**Comment by Wulf** [comment]
Awesome, sounds great @sansx, let me know if you have any questions. Feel free to suggest improvements!

**Comment by sansx** [comment]
Hi, I had switch to vite, and `yarn fullstack` runs well, by the way, the vite plugin about wasm, is used for develop wasm with frontend at same time, so it can't compile frontend to wasm, my bad, so I'm not sure wether you need [this pr](https://github.com/sansx/create-rust-app/tree/vite-template). I'm quite interested in this project, if you need further help, please let me know.(like make a graphql version, etc.) :D

**Comment by Wulf** [comment]
hey @sansx thanks a lot for your work on this, I've taken a brief look over your changes on Friday but I didn't get a chance to try it out and take a deeper dive, I'll do this soon!

Also, with regards to things we can do, I have some items in `docs/TODO.md` that I think the project needs to move forward. Here are some things I would like to have soon:
* Publish documentation on https://create-rust-app.dev (the `docs/` folder has the beginnings of a [docusaurus](https://github.com/facebook/docusaurus) site)
* I'm currently working on getting attachments working (so we can upload to local or s3 buckets easily)
* Tests running for endpoints and frontend end-to-end
* Make libraries instead of `template-*` folders which are copied to the created project

Anyway sorry, I've been busy lately and will try to organize something more formal soon

**Comment by Wulf** [comment]
Just published the documentation website :-)

**Comment by sansx** [comment]
Ohh, that looks great. 

I'm also busy this month, but the lucky thing is switch to vite is not difficult, so I had take some time to finish it, the good news is I had start getting familiar with this project, but busy tho. 

And I think if we talk in this issue, it will be extremely long, and might confuse others user, so I closed this issue, and had look for another contact way but found none of it 😂   

If you think it's ok, we can continue in this issue, or you can send me a email with a contact way, or we just use the email 😉

**Comment by Wulf** [comment]
I'll send you an email!

Also, do you think it's not worth adding vite support now because it doesn't compile to wasm? Is there any other advantage to vite over standard create-react-app?

**Comment by Wulf** [comment]
aaannnddd, we've landed vitejs integration in 6.0.0 :rocket: !

Right now it's only available in `actix-web`, but I'm hoping to add it for `poem` later
