### ISSUE TITLE
Error: could not proxy request <some path> from localhost:3000 to http://localhost:8080/

### ISSUE THREAD

**Issue by craigdrown** [Wulf/create-rust-app#4]
The demo screencast shows the same error without it being obvious how to fix it. Have tried various changes to the "proxy" settings in frontend/package.json without success.
Great project though- thanks!

**Comment by Wulf** [comment]
hey Craig, thanks for the feedback. Those proxy errors should be treated more like warnings; they're not a big deal as the frontend is just complaining that it can't connect to the backend (since it's probably compiling). I think there are three ways to address this:

1) ignore it, unless a specific endpoint you're trying to reach is not working, in which case you should check your HTTP request.
2) don't use the admin/devbox plugin which causes most of these errors since the devbox checks if the backend is up or not.
3) we could try implementing something where the backend isn't restarted until new changes are compiled and ready to run.

Let me know your thoughts and if you'd like to see some other features in the library. I plan to hopefully release a feature which generates react-query hooks automatically so using backend endpoints is a breeze + typed without extra labour. It's been done for a while, I think I just wanted to polish and look over it before shipping.

**Comment by Wulf** [comment]
I'm going to close this issue but please feel free to reopen it!

**Comment by craigdrown** [comment]
@Wulf  - thanks. Yes, patience was the missing ingredient ;-) - Thank you!
