### ISSUE TITLE
WASM?

### ISSUE THREAD

**Issue by ivanschuetz** [Wulf/create-rust-app#45]
Just saw this project and thought that it would be cool if there was an option to generate a Rust WASM project that interfaces with the React app? So React is only UI and all the logic is in the WASM app and it can share code with the backend?

**Comment by Wulf** [comment]
I like this idea and it is definitely possible, what kind of logic were you thinking of sharing between the backend and frontend? 

Although it hasn’t been common in my experience, there are definitely times when things like parsers or [de]serializers can be written once and used twice instead of re-writing for back- or frontend. 

I have a feeling some users could benefit from this — I can help guide you in implementing this if you’re up for it! I think we can add it in as an opt-in option.

**Comment by Wulf** [comment]
I'm going to close this, but please feel free to re-open it if you'd like to continue the discussion :)
