### ISSUE TITLE
Template mailer settings query

### ISSUE THREAD

**Issue by katherine-sussol** [Wulf/create-rust-app#7]
Great project, have enjoyed using it - thanks! 

I've got a query about some of the mailer settings that are used in the project:

It looks like there's an environment variable, `SEND_EMAIL` checked here:
https://github.com/Wulf/create-rust-app/blob/321b726359d679c64251504cb635ecc045e87ce3/template/backend/mail/mod.rs#L27

But further down there is some validation that looks for a different environment variable `SEND_MAIL`:
https://github.com/Wulf/create-rust-app/blob/321b726359d679c64251504cb635ecc045e87ce3/template/backend/mail/mod.rs#L65

Was it intended for there to be two different settings to control separate behaviours? The check also appears to print an error message (that at face value sounds contradictory) if `SEND_MAIL` is set to true.

**Comment by Wulf** [comment]
hey @katherine-sussol , thanks for reporting this!

That's a bug 😅. There should be a `!` in front of `std::env::var("SEND_MAIL").unwrap().eq("true")`!

It's this line right here that needs to change:
https://github.com/Wulf/create-rust-app/blob/main/template/backend/mail/mod.rs#L65

Feel free to create a PR, otherwise, I can do it as well :-)

We're going to make some changes which make it easier for these bug fixes to propagate to existing `create-rust-app` projects.
