### ISSUE TITLE
Generated cargo.toml has out of date dependencies

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [Wulf/create-rust-app#70]
As said in the title, the dependencies in the generated cargo.toml file are out of date, I'll soon be making a pull request that updates the dsync and tsync versions (as those are the most critical), and I can make another one that updates the rest of the dependencies too if that'd be helpful

**Comment by Wulf** [comment]
Thanks for reporting this; see my comments in the PR above

**Comment by XChikuX** [comment]
Are you planning on adding [dependabot](https://github.com/features/security) @Wulf to automate this in the future?
It's free for basic stuff and generates PR's to solve annoying dependency issues like this.

**Comment by AnthonyMichaelTDM** [comment]
I highly recommend using dependabot, #86 includes a config file so all you need to do is enable it and dependencies will be scanned for updates every day

**Comment by Wulf** [comment]
Friends, thanks for bringing attention to this. I initially set the version to "1" and "0" for `tsync` and `dsync` respectively because cargo will automatically get the latest versions for both crates when the project is created. This _should_ be happening in the `cargo install` step; if it is not, then that's a bug. Users can call "cargo update" on the package (`cargo update -p tsync`) to update it manually after that. Alternatively, they may manually hard code the version in their generated `Cargo.toml`. The problem with specifying a version is that it becomes the maintainer's job to make sure it's up-to-date which becomes difficult and will require new releases everytime dsync/tsync get updated.

**Comment by Wulf** [comment]
@AnthonyMichaelTDM I created a PR to revert the commit that made this change. Could you clarify whether or not `tsync = "1"` will not use the latest tsync (just released `1.6.1` now) in a generated project?

**Comment by AnthonyMichaelTDM** [comment]
for me it used version 1.6.0

![image](https://user-images.githubusercontent.com/68485672/213903586-d5121a67-fe80-485d-9cda-f0cfd93e779b.png)

**Comment by AnthonyMichaelTDM** [comment]
I'll mark this as closed once we merge #89
